### ISSUE TITLE
A error when run the dynGENIE3_R

### ISSUE THREAD

**Issue by ShellyCoder** [vahuynh/dynGENIE3#1]
1. A warning signed that variable may be used uninitialized occur when i complie C code with 'R CMD SHLIB dynGENIE3.c'.  It's a root that lead to the next error in the fig2.
![1](https://user-images.githubusercontent.com/49678387/62302697-62b6cd80-b4ad-11e9-8c9a-1e779ac8a52b.png)

2. LoadLibrary failure with the dynGENIE3.so
![2](https://user-images.githubusercontent.com/49678387/62303057-0d2ef080-b4ae-11e9-87eb-71d912570930.png)

I'll appreciate your help, if you can reply me on your convenience.

**Comment by vvelasqz** [comment]
I had the same issue with my instalation in windows. The compilation generated a .dll file, so I canged the extension to .so and it worked after that.

I hope this helps
