### ISSUE TITLE
Advice on how to input different conditions and replicates

### ISSUE THREAD

**Issue by rbatorsky** [vahuynh/dynGENIE3#2]
Hello,

I was hoping that you would have time to give some advice on how to input different conditions and replicates to dynGENIE3. I'm successfully running the R implementation on my time series RNAseq data. However, I'm not quite sure the recommended way to input the different replicates and conditions.

My data is:
6 time points
8 conditions plus control
2-3 replicates per condition.

The way I am doing it now, I am inputting each condition and replicate as a separate time series and treating control as a separate condition and running them all at once. Do you recommend this, or to separate conditions into different runs and perhaps treat the control as steady state data?

Thank you for the helpful tool!
Best,
Rebecca

**Comment by vahuynh** [comment]
Hello Rebecca,

Apologies for the very late response.

I think that the best solution would be to have one time series per condition (using indeed the control as a separate condition) and use the mean (or median) expression over the replicates at each time point.

Best,
Vân Anh
