### ISSUE TITLE
Error using alpha = "from.data"

### ISSUE THREAD

**Issue by M-Marku** [vahuynh/dynGENIE3#6]
Hi, 

I am using dynGENIE3 on a 6-sample dataset, with 5 time points each. While setting `alpha = fixed_value` works perfectly, using `alpha = "from.data"` gives 

```
Error in { :
task 2 failed - "NA/NaN/Inf in foreign function call (arg 4)"
```

Any idea where this error comes from, and how to solve it? 
Thanks

**Comment by vahuynh** [comment]
Hi,

I would need a bit more info.

Could you run the following:
`alphas <- estimate.decay.rates(TS.data, time.points)`,
where `TS.data` and `time.points` are the same input arguments as when calling `dynGENIE3(TS.data, time.points)`,
and check if `alphas`has some nan or inf values?

**Comment by M-Marku** [comment]
Indeed, there were a few `NaN` values of alphas for some genes. 
Thank you for your fast reply and your help.
